### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by cmbant** [alessiospuriomancini/cosmopower#29]
Cf. https://github.com/simonsobs/SOLikeT/issues/182

**Comment by alessiospuriomancini** [comment]
Thanks @cmbant. This has now been fixed in commit [65fa9d6](https://github.com/alessiospuriomancini/cosmopower/commit/65fa9d6918255252a150693c79db5523bd4cbb22) and incorporated in the new `v0.2.0` release. Note that python versions up to 3.11 are supported. `python=3.12` is currently in [bugfix](https://devguide.python.org/versions/) and support for it will likely be added in #28. 
Feel free to re-open if still having issues.
